### ISSUE TITLE
Background doesn't work

### ISSUE THREAD

**Issue by Sidthecoder** [talonbragg/Custom-Markup#26]
![image](https://cloud.githubusercontent.com/assets/16711414/22349223/a0959efa-e3c3-11e6-8c77-0be8869232a3.png)
This is that happens when you go on custom markup.

**Comment by talonbragg** [comment]
Sid, we changed the background to a gradient with css. We did this because
the background wasn't working on mobile AND the background image was
bringing cookies from other sites making Custom Markup not secure. Now that
we use the gradient background, all of our ssl servers and the ssl
certificate, are now back in order.

[image: --]




<https://about.me/talonbragg?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by talonbragg** [comment]
I am going to close this because this has been resolved.

**Comment by Sidthecoder** [comment]
Oh

**Comment by Sidthecoder** [comment]
The gradient looks better anyway

**Comment by talonbragg** [comment]
Yeah
